<a href="https://colab.research.google.com/github/vishakha1221/datascience-practical/blob/main/Practical3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Creating a single-dimensional array
a = np.array([1,2,3]) # Calling the array function
print(a)

[1 2 3]


In [ ]:
b = np.array([[1,2], [3,4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
# Creating an ndarray by wrapping a list
list1 = [1,2,3,4,5] # Creating a list
arr = np.array(list1) # Wrapping the list
print(arr)

[1 2 3 4 5]


In [ ]:
# Creating an array of numbers of a specified range
arr1 = np.arange(10, 100) # Array of numbers from 10 up to and excluding 100
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [ ]:
# Creating a 5x5 array of zeroes
arr2 = np.zeros((5,5))
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Creating a linearly spaced vector, with spacing
vector = np.linspace(0, 20, 5) # Start, stop, step
print(vector)

[ 0.  5. 10. 15. 20.]


In [ ]:
# Creating Arrays from Existing Data
x = [1,2,3]
# Used for converting Python sequences into ndarrays
c = np.asarray(x) #np.asarray(a, dtype = None, order = None)
print(c)

[1 2 3]


In [ ]:
# Converting a linear array of 8 elements into a 2x2x2 3D array
arr3 = np.zeros(8) # Flat array of eight zeroes
arr3d = arr3.reshape((2,2,2)) # Restructured array
print(arr3d)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [ ]:
# Flatten rgw 3d array to get back the linear array
arr4 = arr3d.ravel()
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# NumPy array indexing is identical to Python's indexing scheme
arr5 = np.arange(2, 20)
element = arr5[6]
print(element)

8


In [ ]:
# Python's concept of lists slicing is extended to NumPy.
# The slice object is constructed by providing start, stop, and step parameters to slice()
arr6 = np.arange(20)
arr_slice = slice(1, 10, 2) # Start, stop & step
element2 = arr6[6]
print(arr6[arr_slice])

[1 3 5 7 9]


In [ ]:
# Slicing items beginning with a specified index
arr7 = np.arange(20)
print(arr7[2:])

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Slicing items until a specified index
print(arr7[:15])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
# Extracting specific rows and columns using Slicing
d = np.array([[1,2,3], [3,4,5], [4,5,6]])
print(d[0:2, 0:2]) # Slice the first two rows and the first two columns

[[1 2]
 [3 4]]


In [ ]:
print(d.shape) # Returns a tuple consisting of array dimensions
print(d.ndim) # Attribute returns the number of array dimensions
print(a.itemsize) # Returns the length of each element of array in bytes

(3, 3)
2
8


In [ ]:
y = np.empty([3,2], dtype = int) # Creates an uninitialized array of specified shape and dtype
print(y)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
# Returns a new array of specified size, filled with zeros
z = np.zeros(5) # np.zeros(shape, dtype = float)
print(z)

[0. 0. 0. 0. 0.]


In [ ]:
# NumPy provides the option of importing data from files directly into ndarray using the loadtxt function
# The savetxt function can be used to write data from an array into a text file
#import os
#print(os.listdir('../input'))
arr_txt = np.loadtxt('./data_test.txt')
np.savetxt('newfilex.txt', arr_txt)

ValueError: could not convert string 'account_number,name,item_code,category,quantity,unit' to float64 at row 0, column 1.

In [ ]:
# NumPy arrays can be dumped into CSV files using the savetxt function and the comma delimiter
# The genfromtxt function can be used to read data from a CSV file into a NumPy array
arr_csv = np.genfromtxt('Hurricanes.csv', delimiter = ',')
np.savetxt('newfilex.csv', arr_csv, delimiter = ',')

In [ ]:
import pandas as pd

In [ ]:
# Creating an empty Series
series = pd.Series() # The Series() function creates a new Series
print(series)

Series([], dtype: object)


In [ ]:
# Creating a series from an ndarray
# Note that indexes are a assigned automatically if not specifies
arr = np.array([10,20,30,40,50])
series1 = pd.Series(arr)
print(series1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
# Creating a series from a Python dict
# Note that the keys of the dictionary are used to assign indexes during conversion
data = {'a':10, 'b':20, 'c':30}
series2 = pd.Series(data)
print(series2)

a    10
b    20
c    30
dtype: int64


In [ ]:
# Retrieving a part of the series using slicing
print(series1[1:4])

1    20
2    30
3    40
dtype: int64


In [ ]:
# Converting a list into a DataFrame
list1 = [10, 20, 30, 40]
table = pd.DataFrame(list1)
print(table)

    0
0  10
1  20
2  30
3  40


In [ ]:
# Creating a DataFrame from a list of dictionaries
data = [{'a':1, 'b':2}, {'a':2, 'b':4, 'c':8}]
table1 = pd.DataFrame(data)
print(table1)

   a  b    c
0  1  2  NaN
1  2  4  8.0


In [ ]:
# Creating a DataFrame from a list of dictionaries and accompaying row indices
table2 = pd.DataFrame(data, index = ['first', 'second'])
# Dict keys become column lables
print(table2)

        a  b    c
first   1  2  NaN
second  2  4  8.0


In [ ]:
# Converting a dictionary of series into a DataFrame
data1 = {'one':pd.Series([1,2,3], index = ['a', 'b', 'c']),
        'two':pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])}
table3 = pd.DataFrame(data1)
print(table3)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


In [ ]:
# A new column can be added to a DataFrame when the data is passed as a Series
table3['three'] = pd.Series([10,20,30], index = ['a', 'b', 'c'])
print(table3)

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN


In [ ]:
# DataFrame columns can be deleted using the del() function
del table3['one']
print(table3)

   two  three
a    1   10.0
b    2   20.0
c    3   30.0
d    4    NaN


In [ ]:
# DataFrame columns can be deleted using the pop() function
table3.pop('two')
print(table3)

   three
a   10.0
b   20.0
c   30.0
d    NaN


In [ ]:
# DataFrame rows can be selected by passing the row lable to the loc() function
print(table3.loc['c'])

three    30.0
Name: c, dtype: float64


In [ ]:
# Row selection can also be done using the row index
print(table3.iloc[2])

three    30.0
Name: c, dtype: float64


In [ ]:
# The append() function can be used to add more rows to the DataFrame
data2 = {'one':pd.Series([1,2,3], index = ['a', 'b', 'c']),
        'two':pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])}
table5 = pd.DataFrame(data2)
table5['three'] = pd.Series([10,20,30], index = ['a', 'b', 'c'])
row = pd.DataFrame([[11,13],[17,19]], columns = ['two', 'three'])
# table6 = table5.append(row)
table6 = pd.concat([table5,row])
print(table6)

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
0  NaN   11   13.0
1  NaN   17   19.0


In [ ]:
# The drop() function can be used to drop rows whose labels are provided
table7 = table6.drop('a')
print(table7)

   one  two  three
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
0  NaN   11   13.0
1  NaN   17   19.0


In [ ]:
# Data can be loaded into DataFrames from input data stored in the CSV format using the read_csv() function
table_csv = pd.read_csv('Cars2015.csv')

In [ ]:
# Data present in DataFrames can be written to a CSV file using the to_csv() function
# If the specified path doesn't exist, a file of the same name is automatically created
table_csv.to_csv('newcars2015.csv')

In [ ]:
# Data can be loaded into DataFrames from input data stored in the Excelsheet format using read_excel()
sheet = pd.read_excel('cars2015.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'cars2015.xlsx'

In [ ]:
# Data present in DataFrames can be written to a spreadsheet file using to_excel()
#If the specified path doesn't exist, a file of the same name is automatically created
sheet.to_excel('newcars2015.xlsx')

NameError: name 'sheet' is not defined